import json
from pathlib import Path

notebook_path = Path(r'd:\DATATHON\notebooks\namnn.ipynb')

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 16 Update (Trend)
new_source_16 = [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from pathlib import Path\n",
    "\n",
    "base_dir = Path.cwd()\n",
    "root_dir = None\n",
    "for _ in range(5):\n",
    "    if (base_dir / 'data').exists():\n",
    "        root_dir = base_dir\n",
    "        break\n",
    "    base_dir = base_dir.parent\n",
    "\n",
    "if root_dir is None:\n",
    "    raise FileNotFoundError('Không tìm thấy thư mục data trong cây thư mục hiện tại')\n",
    "\n",
    "sales_path = root_dir / 'data' / 'raw' / 'sales.csv'\n",
    "\n",
    "if sales_path.exists():\n",
    "    print(f'Đang sử dụng dữ liệu từ: {sales_path}')\n",
    "    df_sales = pd.read_csv(sales_path, parse_dates=['Date'])\n",
    "    df_sales['month'] = df_sales['Date'].dt.to_period('M')\n",
    "    df_sales['week'] = df_sales['Date'].dt.to_period('W')\n",
    "\n",
    "    monthly_revenue = df_sales.groupby('month', as_index=False).agg({\n",
    "        'Revenue': 'sum',\n",
    "        'COGS': 'sum'\n",
    "    }).sort_values('month')\n",
    "    monthly_revenue['net_profit'] = monthly_revenue['Revenue'] - monthly_revenue['COGS']\n",
    "\n",
    "    weekly_revenue = df_sales.groupby('week', as_index=False).agg({\n",
    "        'Revenue': 'sum',\n",
    "        'COGS': 'sum'\n",
    "    }).sort_values('week')\n",
    "    weekly_revenue['net_profit'] = weekly_revenue['Revenue'] - weekly_revenue['COGS']\n",
    "\n",
    "    print('Bảng doanh thu theo tháng (từ sales.csv):')\n",
    "    display(monthly_revenue)\n",
    "    print('Bảng doanh thu theo tuần (từ sales.csv):')\n",
    "    display(weekly_revenue)\n",
    "else:\n",
    "    raise FileNotFoundError(f'Không tìm thấy file {sales_path}')\n",
    "\n",
    "# Vẽ biểu đồ doanh thu theo tuần (Revenue và Net Profit)\n",
    "plt.figure(figsize=(14, 6))\n",
    "plt.plot(weekly_revenue['week'].astype(str), weekly_revenue['Revenue'] / 1e9, marker='.', linestyle='-', label='Revenue (tỷ)')\n",
    "plt.plot(weekly_revenue['week'].astype(str), weekly_revenue['net_profit'] / 1e9, marker='.', linestyle='--', label='Net Profit (tỷ)')\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "plt.title('Doanh thu & Lợi nhuận ròng theo tuần (Nguồn: Sales Table)')\n",
    "plt.xlabel('Tuần')\n",
    "plt.ylabel('Giá trị (tỷ)')\n",
    "plt.grid(True, linestyle='--', alpha=0.5)\n",
    "plt.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Vẽ biểu đồ doanh thu theo tháng (Revenue và Net Profit)\n",
    "plt.figure(figsize=(12, 5))\n",
    "plt.plot(monthly_revenue['month'].astype(str), monthly_revenue['Revenue'] / 1e9, marker='o', linestyle='-', label='Revenue (tỷ)')\n",
    "plt.plot(monthly_revenue['month'].astype(str), monthly_revenue['net_profit'] / 1e9, marker='o', linestyle='--', label='Net Profit (tỷ)')\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "plt.title('Doanh thu & Lợi nhuận ròng theo tháng (Nguồn: Sales Table)')\n",
    "plt.xlabel('Tháng')\n",
    "plt.ylabel('Giá trị (tỷ)')\n",
    "plt.grid(True, linestyle='--', alpha=0.5)\n",
    "plt.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]

# Cell 17 Update (Promotion)
new_source_17 = [
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "base_dir = Path.cwd()\n",
    "root_dir = None\n",
    "for _ in range(5):\n",
    "    if (base_dir / 'data').exists():\n",
    "        root_dir = base_dir\n",
    "        break\n",
    "    base_dir = base_dir.parent\n",
    "\n",
    "items_path = root_dir / 'data' / 'raw' / 'order_items.csv'\n",
    "products_path = root_dir / 'data' / 'raw' / 'products.csv'\n",
    "promos_path = root_dir / 'data' / 'raw' / 'promotions.csv'\n",
    "\n",
    "print(f'Loading data from raw tables...')\n",
    "items_df = pd.read_csv(items_path)\n",
    "products_df = pd.read_csv(products_path)\n",
    "promos_df = pd.read_csv(promos_path)\n",
    "\n",
    "# Join to get revenue and COGS at item level\n",
    "df = items_df.merge(products_df[['product_id', 'cogs']], on='product_id', how='left')\n",
    "df = df.merge(promos_df[['promo_id', 'promo_type', 'promo_channel']], left_on='promotion_id', right_on='promo_id', how='left')\n",
    "\n",
    "# Calculate line revenue and profit\n",
    "df['line_revenue'] = df['quantity'] * df['unit_price'] - df['discount_amount']\n",
    "df['line_cogs'] = df['quantity'] * df['cogs']\n",
    "df['net_profit'] = df['line_revenue'] - df['line_cogs']\n",
    "\n",
    "promo_only_df = df[df['promotion_id'] != 'NO_PROMO'].copy()\n",
    "\n",
    "print('\\n=== PHÂN TÍCH THEO PROMOTION TYPE (Dựa trên Order Items) ===')\n",
    "promo_type_summary = (\n",
    "    promo_only_df\n",
    "    .groupby('promo_type', as_index=False)\n",
    "    .agg(\n",
    "        total_revenue=('line_revenue','sum'),\n",
    "        total_net_profit=('net_profit','sum'),\n",
    "        order_count=('order_id','nunique')\n",
    "    )\n",
    "    .sort_values('total_revenue', ascending=False)\n",
    ")\n",
    "display(promo_type_summary)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n",
    "axes[0].bar(promo_type_summary['promo_type'], promo_type_summary['total_revenue']/1e9, label='Revenue (tỷ)')\n",
    "axes[0].bar(promo_type_summary['promo_type'], promo_type_summary['total_net_profit']/1e9, label='Net Profit (tỷ)', alpha=0.7)\n",
    "axes[0].set_title('Doanh thu & Lợi nhuận theo Promo Type')\n",
    "axes[0].legend()\n",
    "\n",
    "promo_channel_summary = (\n",
    "    promo_only_df\n",
    "    .groupby('promo_channel', as_index=False)\n",
    "    .agg(\n",
    "        total_revenue=('line_revenue','sum'),\n",
    "        total_net_profit=('net_profit','sum')\n",
    "    )\n",
    "    .sort_values('total_revenue', ascending=False)\n",
    ")\n",
    "axes[1].bar(promo_channel_summary['promo_channel'], promo_channel_summary['total_revenue']/1e9, color='green', label='Revenue (tỷ)')\n",
    "axes[1].bar(promo_channel_summary['promo_channel'], promo_channel_summary['total_net_profit']/1e9, color='red', label='Net Profit (tỷ)', alpha=0.7)\n",
    "axes[1].set_title('Doanh thu & Lợi nhuận theo Promo Channel')\n",
    "axes[1].legend()\n",
    "plt.show()\n"
]

# Cell 18 Update (Demographic)
new_source_18 = [
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "base_dir = Path.cwd()\n",
    "root_dir = None\n",
    "for _ in range(5):\n",
    "    if (base_dir / 'data').exists():\n",
    "        root_dir = base_dir\n",
    "        break\n",
    "    base_dir = base_dir.parent\n",
    "\n",
    "items_path = root_dir / 'data' / 'raw' / 'order_items.csv'\n",
    "products_path = root_dir / 'data' / 'raw' / 'products.csv'\n",
    "customers_path = root_dir / 'data' / 'raw' / 'customers.csv'\n",
    "orders_path = root_dir / 'data' / 'raw' / 'orders.csv'\n",
    "\n",
    "print('Loading data from raw tables for demographic analysis...')\n",
    "items_df = pd.read_csv(items_path)\n",
    "products_df = pd.read_csv(products_path)\n",
    "customers_df = pd.read_csv(customers_path)\n",
    "orders_df = pd.read_csv(orders_path)\n",
    "\n",
    "# Join tables\n",
    "df = items_df.merge(products_df[['product_id', 'cogs', 'category']], on='product_id', how='left')\n",
    "df = df.merge(orders_df[['order_id', 'customer_id']], on='order_id', how='left')\n",
    "df = df.merge(customers_df[['customer_id', 'gender', 'age_group']], on='customer_id', how='left')\n",
    "\n",
    "df['line_revenue'] = df['quantity'] * df['unit_price'] - df['discount_amount']\n",
    "df['line_cogs'] = df['quantity'] * df['cogs']\n",
    "df['net_profit'] = df['line_revenue'] - df['line_cogs']\n",
    "\n",
    "print('=== PHÂN TÍCH NHÂN KHẨU HỌC KHÁCH HÀNG (Dựa trên Raw Data) ===\\n')\n",
    "\n",
    "# 1. Phân bố theo giới tính\n",
    "gender_summary = (\n",
    "    df.groupby('gender', as_index=False)\n",
    "    .agg(\n",
    "        total_revenue=('line_revenue','sum'),\n",
    "        total_net_profit=('net_profit','sum'),\n",
    "        unique_customers=('customer_id','nunique'),\n",
    "    )\n",
    "    .sort_values('total_revenue', ascending=False)\n",
    ")\n",
    "display(gender_summary)\n",
    "\n",
    "# 2. Phân bố theo nhóm tuổi\n",
    "age_summary = (\n",
    "    df.groupby('age_group', as_index=False)\n",
    "    .agg(\n",
    "        total_revenue=('line_revenue','sum'),\n",
    "        total_net_profit=('net_profit','sum'),\n",
    "        unique_customers=('customer_id','nunique'),\n",
    "    )\n",
    "    .sort_values('total_revenue', ascending=False)\n",
    ")\n",
    "display(age_summary)\n",
    "\n",
    "# 3. Heatmap: Revenue by Gender and Age Group\n",
    "pivot_df = df.pivot_table(index='age_group', columns='gender', values='line_revenue', aggfunc='sum')\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.heatmap(pivot_df / 1e9, annot=True, fmt='.2f', cmap='YlGnBu')\n",
    "plt.title('Doanh thu theo Giới tính và Nhóm tuổi (tỷ đồng)')\n",
    "plt.show()\n"
]

updated_cells = 0
for cell in nb['cells']:
    if cell['cell_type'] == 'code':
        cid = cell.get('id')
        if cid == 'dafedf58':
            cell['source'] = new_source_16
            updated_cells += 1
        elif cid == 'c85e8dc4':
            cell['source'] = new_source_17
            updated_cells += 1
        elif cid == '98018397':
            cell['source'] = new_source_18
            updated_cells += 1

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f'Successfully updated {updated_cells} cells.')
